frames = \
[
    {
        "index": 2,
        "orig_sentence": "The trophy doesn't fit into the brown suitcase because [it] is too large/small.",
        "entities": ["trophy", "suitcase"],
        "entity_substitutes": [["ball", "toy"], ["bag", "box"]],
        "determiner": "the",
        "packed_relations": ["doesn't fit into/can fit into", "doesn't hold/can hold"],
        "packed_relation_substitutes": [["can't be put into/can be put into"], ["doesn't have enough room for/has enough room for"]],
        "packed_predicates": ["is large/isn't large", "is small/isn't small"],
    },
    {
        "index": 4,
        "orig_sentence": "Joan made sure to thank Susan for all the help [she] had recieved/given.",
        "entities": ["John", "Susan"],
        "entity_substitutes": [["David", "Michael"], ["Mary", "Tiffany"]],
        "packed_relations": ["thanked/didn't thank", "took good care of/didn't good care of"],
        "packed_relation_substitutes": [["felt grateful to/didn't feel grateful to"], ["was appreciated by/wasn't appreciated by"]],
        "packed_predicates": ["had received a lot of help/hadn't received a lot of help", "had given a lot of help/hadn't given a lot of help"],
        "predicate_dichotomy": False,
    },
    {
        "index": 4000,
        "orig_sentence": "John gave a lot of money to Susan because [he] was very rich/poor.",
        "entities": ["John", "Susan"],
        "entity_substitutes": [["David", "Michael"], ["Mary", "Linda"]],
        "packed_relations": ["gave a lot of money to/didn't give a lot of money to", "received a lot of money from/didn't receive a lot of money from"],
        "packed_relation_substitutes": [["subsidized/didn't subsidize"], ["borrowed a lot of money from/didn't borrow any money from"]],
        "packed_predicates": ["was rich/wasn't rich", "was poor/wasn't poor"],
    },
    {
        "index": 10,
        "orig_sentence": "The delivery truck zoomed by the school bus because [it] was going so fast/slow.",
        "entities": ["truck", "bus"],
        "entity_substitutes": [["car", "ambulance"], ["bicycle", "tram"]],
        "determiner": "the",
        "packed_relations": ["overtook/couldn't overtake", "fell far behind/didn't fall far behind"],
        "packed_relation_substitutes": [["zoomed by/didn't pass"], ["was left behind/wasn't left far behind"]],
        "packed_predicates": ["was going fast/wasn't going fast", "was going slow/wasn't going slow"],
    },
    ## didn't defeated, replace error: didn't defeat -> defeated
    {
        "index": 12,
        "orig_sentence": "Frank felt vindicated/crushed when his longtime rival Bill revealed that [he] was the winner of the competition.",
        "entities": ["John", "Susan"],
        "entity_substitutes": [["David", "Michael"], ["Mary", "Linda"]],
        "packed_relations": ["beat/didn't beat", "lost to/didn't lose to"],
        "packed_relation_substitutes": [["defeated/didn't defeat"], ["was defeated by/wasn't defeated by"]],
        "relation_suffix": "in the game",
        "packed_predicates": ["was happy/wasn't happy", "was sad/wasn't sad"],
        "reverse_causal": True
    },
    {
        "index": 16,
        "orig_sentence": "The large ball crashed right through the table because [it] was made of steel/styrofoam.",
        "entities": ["ball", "board"],
        "entity_substitutes": [["bullet", "arrow"], ["shield", "disk"]],
        "determiner": "the",
        "packed_relations": ["crashed right through/didn't crash through", "failed to block/blocked"],
        "packed_relation_substitutes": [["penetrated through/didn't penetrate through"], ["failed to stop/stopped"]],
        "packed_predicates": ["was hard/wasn't hard", "was soft/wasn't soft"],
    },
    {
        "index": 18,
        "orig_sentence": "John couldn't see the stage with Billy in front of him because [he] is so short.",
        "entities": ["John", "Susan"],
        "entity_substitutes": [["David", "Edward"], ["Betty", "Donna"]],
        "packed_relations": ["couldn't see the stage behind/could see the stage behind", "blocked the view of/didn't block the view of"],
        "packed_relation_substitutes": [["couldn't catch sight of the stage behind/could catch sight of the stage behind"], ["obstructed the sight of/didn't obstruct the sight of"]],
        "packed_predicates": ["is short/isn't short", "is tall/isn't tall"],
    },
    {
        "index": 20,
        "orig_sentence": "Tom threw his schoolbag down to Ray after [he] reached the top of the stairs.",
        "entities": ["Brian", "Amy"],
        "entity_substitutes": [["Charles", "Paul"], ["Emma", "Linda"]],
        "packed_relations": ["threw the schoolbag down to/threw the schoolbag up to", "caught the schoolbag thrown down by/caught the schoolbag thrown up by"],
        "packed_relation_substitutes": [["cast the schoolbag down to/cast the schoolbag up to"], ["took the schoolbag thrown down by/took the schoolbag thrown up by"]],
        "packed_predicates": ["reached the top of the stairs", "reached the bottom of the stairs"],
        "conjunctions": [["after", ], ["before", ]]
    },
    ## didn't defeated, replace error: didn't defeat -> defeated
    {
        "index": 22,
        "orig_sentence": "Although they ran at about the same speed, Sue beat Sally because [she] had such a good start.",
        "entities": ["Tom", "Sue"],
        "entity_substitutes": [["John", "David"], ["Sally", "Susan"]],
        "packed_relations": ["beat/didn't beat", "lost to/didn't lose to"],
        "packed_relation_substitutes": [["defeated/didn't defeat"], ["was defeated by/wasn't defeated by"]],
        "relation_prefix": "Running at about the same speed,",
        "relation_suffix": "in the running race",
        "packed_predicates": ["had a good start/didn't have a good start", "had a bad start/didn't have a bad start"],
    },
    {
        "index": 28,
        "orig_sentence": "Anna did a lot better than her good friend Lucy on the test because [she] had studied so hard.",
        "entities": ["Anna", "Andy"],
        "entity_substitutes": [["Lucy", "Nancy"], ["George", "Frank"]],
        "packed_relations": ["did better than/didn't do better than", "did worse than/didn't do worse than"],
        "packed_relation_substitutes": [["performed better than/didn't perform better than"], ["performed worse than/didn't perform worse than"]],
        "relation_suffix": "on the test",
        "packed_predicates": ["had studied hard/hadn't studied hard", "was lazy in doing homework/wasn't lazy in doing homework"],
    },
    {
        "index": 30,
        "orig_sentence": "The firemen arrived after the police because [they] were coming from so far away.",
        "entities": ["doctor", "police"],
        "entity_substitutes": [["worker", "employee"], ["boss", "administrator"]],
        "determiner": "the",
        "packed_relations": ["arrived after/didn't arrive after", "arrived before/didn't arrive before"],
        "packed_relation_substitutes": [["reached here after/didn't reach here after"], ["reached here before/didn't reach here before"]],
        "packed_predicates": ["came from far away/didn't come from far away", "came from a close place/didn't come from a close place"],
    },
    {
        "index": 32000,
        "orig_sentence": "Frank was upset with Tom because the toaster [he] had bought from him didn't work.",
        "entities": ["Betty", "Henry"],
        "entity_substitutes": [["Amy", "Linda"], ["Bush", "Frank"]],
        "packed_relations": ["was upset with/was pleased with", "was hated by/was loved by"],
        "packed_relation_substitutes": [["hated/liked"], ["was disliked by/was liked by"]],
        "packed_predicates": ["had bought didn't work/had bought worked well", "had sold didn't work/had sold worked well"],
        "predicate_prefix": "the toaster",
        "predicate_dichotomy": False,
    },
    {
        "index": 36,
        "orig_sentence": "The sack of potatoes had been placed above the bag of flour, so [it] had to be moved first",
        "entities": ["potatoes", "flour"],
        "entity_substitutes": [["candy", "rice"], ["beans", "noodles"]],
        "determiner": "the bag of",
        "packed_relations": ["had been placed above/hadn't been placed above", "had been placed below/hadn't been placed below"],
        "packed_relation_substitutes": [["had been put above/hadn't been put above"], ["had been put below/hadn't been put below"]],
        "packed_predicates": ["had to be moved first/couldn't be moved first", "had to be moved later/couldn't be moved later"],
        "reverse_causal": True
    },
    {
        "index": 38,
        "orig_sentence": "Pete envies Martin although [he] is very successful.",
        "entities": ["Peter", "Mandy"],
        "entity_substitutes": [["Martin", "Paul"], ["Cindy", "Emma"]],
        "packed_relations": ["envied/didn't envy", "was envied by/wasn't envied by"],
        "packed_relation_substitutes": [["was jealous of/wasn't jealous of"], ["was admired by/wasn't admired by"]],
        "packed_predicates": ["failed/didn't fail", "was successful/wasn't successful"],
    },
    {
        "index": 42,
        "orig_sentence": "I poured water from the bottle into the cup until [it] was empty.",
        "entities": ["bottle", "cup"],
        "entity_substitutes": [["bowl", "bucket"], ["tube", "container"]],
        "determiner": "the",
        "packed_relations": ["was filled with water from/leaked into", "leaked into/was filled with water from"],
        "packed_relation_substitutes": [["was suffused with water from/dripped water into"], ["dripped water into/was suffused with water from"]],
        "packed_predicates": ["was empty", "was full"],
        "conjunctions": [["after", ], ["before", ]]
    },
    {
        "index": 50,
        "orig_sentence": "Joe's uncle can still beat him at tennis, even though [he] is 30 years younger.",
        "entities": ["Joe", "Amy"],
        "entity_substitutes": [["David", "Charles"], ["Betty", "Cindy"]],
        "packed_relations": ["can beat/can't beat", "often loses to/seldom loses to"],
        "packed_relation_substitutes": [["can defeat/can't defeat"], ["is often defeated by/is seldom defeated by"]],
        "relation_suffix": "at tennis",
        "packed_predicates": ["is older/isn't older", "is younger/isn't younger"],
    },
    {
        "index": 68,
        "orig_sentence": "Ann asked Mary what time the library closes, because [she] had forgotten.",
        "entities": ["Ann", "Henry"],
        "entity_substitutes": [["Mary", "Linda"], ["Brian", "Michael"]],
        "packed_relations": ["asked/didn't ask", "told/didn't tell"],
        "packed_relation_substitutes": [["was told by/wasn't told by"], ["was asked by/wasn't asked by"]],
        "relation_suffix": "what time the library closes",
        "packed_predicates": ["had forgotten/hadn't forgotten", "remembered/didn't remember"],
    },
    {
        "index": 84,
        "orig_sentence": "If the con artist has succeeded in fooling Sam, [he] would have gotten a lot of money.",
        "entities": ["Sam", "Emma"],
        "entity_substitutes": [["Paul", "Bush"], ["Susan", "Lucy"]],
        "packed_relations": ["succeeded in fooling/failed to fool", "was fooled by/wasn't fooled by"],
        "packed_relation_substitutes": [["succeeded in cheating/failed to cheat"], ["was cheated by/wasn't cheated by"]],
        "packed_predicates": ["got a lot of money/didn't get a lot of money", "lost a lot of money/didn't lose a lot of money"],
        "predicate_dichotomy": False,
        "reverse_causal": True
    },  
    {
        "index": 15000,
        "orig_sentence": "Jackson was greatly influenced by Arnold, though [he] lived two centuries later.",
        "entities": ["Jack", "Betty"],
        "entity_substitutes": [["Tom", "Jay"], ["Emily", "Helen"]],
        "packed_relations": ["always takes care of/dosen't take care of", "is always taken care of by/isn't taken care of by"],
        "packed_relation_substitutes": [["always looks after/dosen't look after"], ["always needs the help of/didn't need the help of"]],
        "packed_predicates": ["is older/isn't older", "is younger/isn't younger"],
    },
    {
        "index": 160,
        "orig_sentence": "The actress used to be named Terpsichore, but she changed it to Tina a few years ago, because she figured [it] was too hard to pronounce.",
        "entities": ["Betty", "Adele"],
        "entity_substitutes": [["Amy", "Cindy"], ["Alberta", "Caroline"]],
        "packed_relations": ["replaced/didn't replace", "was changed to/wasn't changed to"],
        "packed_relation_substitutes": [["was substituted for/wasn't substituted for"], ["was replaced by/wasn't replaced by"]],
        "relation_suffix": "as the actress's new name",
        "packed_predicates": ["is easy to pronounce/isn't easy to pronounce", "is hard to pronounce/isn't hard to pronounce"],
    },
    {
        "index": 1700000,
        "orig_sentence": "In July, Kamtchatka declared war on Yakutsk. Since Yakutsk's army was much  better equipped and ten times larger, [they] were defeated within weeks.",
        "entities": ["Germany", "Italy"],
        "entity_substitutes": [["Australia", "Japan"], ["Argentina", "Canada"]],
        "packed_relations": ["defeated/didn't defeat", "was defeated by/wasn't defeated by"],
        "packed_relation_substitutes": [["conquered/didn't conquer"], ["was conquered by/wasn't conquered by"]],
        "packed_predicates": ["was more powerful/wasn't more powerful", "was less powerful/wasn't less powerful"],
    },
    {
        "index": 186,
        "orig_sentence": "When the sponsors of the bill got to the town hall, they were surprised to find that the room was full of opponents. [They] were very much in the minority",
        "entities": ["sponsors", "opponents"],
        "entity_substitutes": [["workers", "customers"], ["teachers", "students"]],
        "determiner": "the",
        "packed_relations": ["were less in number than/were not less in number than", "were more in number than/were not more in number than"],
        "packed_relation_substitutes": [["were outnumbered by/were not outnumbered by"], ["outnumbered/didn't outnumber"]],
        "packed_predicates": ["were in the minority/were not in the minority", "were in the majority/were not in the majority"],
        "reverse_causal": True
    },
    {
        "index": 188,
        "orig_sentence": "Everyone really loved the oatmeal cookies; only a few people liked the  chocolate chip cookies. Next time, we should make more of [them] .",
        "entities": ["cookies", "chips"],
        "entity_substitutes": [["apples", "bananas"], ["grapes", "sandwiches"]],
        "determiner": "the",
        "packed_relations": ["are more popular than/are less popular than", "lose to/don't lose to"],
        "packed_relation_substitutes": [["are sold more than/are sold less than"], ["are not as popular as/are as popular as"]],
        "packed_predicates": ["should be made more next time/shouldn't be made more next time", "should be made less next time/shouldn't be made less next time"],
        "reverse_causal": True
    },
    {
        "index": 190,
        "orig_sentence": "We had hoped to place copies of our newsletter on all the chairs in the auditorium, but there were simply not enough of [them] .",
        "entities": ["newspapers", "chairs"],
        "entity_substitutes": [["cups", "pictures"], ["tables", "benches"]],
        "determiner": "the",
        "packed_relations": ["could be placed on all/couldn't be placed on all", "could all be covered by/couldn't all be covered by"],
        "packed_relation_substitutes": [["could be put on all/couldn't be put on all"], ["could carry all/couldn't carry all"]],
        "packed_predicates": ["there were many of/there were not many of", "there were few of/there were not few of"],
        "prepositive_pred": True,
    },
    {
        "index": 19600,
        "orig_sentence": "Steve follows Fred's example in everything. [He] admires him hugely.",
        "entities": ["Steve", "Lucy"],
        "entity_substitutes": [["Fred", "George"], ["Lily", "Wendy"]],
        "packed_relations": ["follows/doesn't follow", "is followed by/isn't followed by"],
        "packed_relation_substitutes": [["imitates/doesn't imitate"], ["is imitated by/isn't imitated by"]],
        "relation_suffix": "in everything",
        "packed_predicates": ["is bad at making decisions/isn't bad at making decisions", "is good at making decisions/isn't good at making decisions"],
    },
    {
        "index": 198,
        "orig_sentence": "The table won't fit through the doorway because [it] is too wide.",
        "entities": ["table", "doorway"],
        "entity_substitutes": [["desk", "sofa"], ["corridor", "hallway"]],
        "determiner": "the",
        "packed_relations": ["will fit through/won't fit through", "will be fitted through by/won't be fitted through by"],
        "packed_relation_substitutes": [["will pass through/won't pass through"], ["will be passed through by/won't be passed through by"]],
        "packed_predicates": ["is narrow/isn't narrow", "is wide/isn't wide"],
    },
    {
        "index": 2000000,
        "orig_sentence": "Grace was happy to trade me her sweater for my jacket. She thinks [it] looks dowdy on her.",
        "entities": ["sweater", "jacket"],
        "entity_substitutes": [["skirt", "cap"], ["hat", "short"]],
        "determiner": "the",
        "packed_relations": ["is traded by Grace for/isn't traded by Grace for", "is substituted by Grace for/isn't substituted by Grace for"],
        "packed_relation_substitutes": [["is replaced by Grace with/isn't replaced by Grace with"], ["is preferred by Grace to/isn't preferred by Grace to"]],
        "packed_predicates": ["looks bad/looks not bad", "looks good/looks not good"],
        "predicate_prefix": "she thinks",
    },
    {
        "index": 226,
        "orig_sentence": "Bill passed the half-empty plate to John because [he] was full.",
        "entities": ["Bill", "Amy"],
        "entity_substitutes": [["Brian", "David"], ["Emma", "Helen"]],
        "packed_relations": ["passed the half-empty plate to/didn't pass the half-empty plate to", "received the half-empty plate from/didn't received the half-empty plate from"],
        "packed_relation_substitutes": [["gave the half-empty plate to/didn't give the half-empty plate to"], ["took the half-empty plate from/didn't take the half-empty plate from"]],
        "packed_predicates": ["was full/wasn't full", "was hungry/wasn't hungry"],
    },
    {
        "index": 252,
        "orig_sentence": "George got free tickets to the play, but he gave them to Eric, even though [he] was particularly eager to see it.",
        "entities": ["George", "Linda"],
        "entity_substitutes": [["Eric", "Ted"], ["Cindy", "Lucy"]],
        "packed_relations": ["gave the tickets of the play to/didn't give the tickets of the play to", "received the tickets of the play from/didn't receive the tickets of the play from"],
        "packed_relation_substitutes": [["sent the tickets of the play to/didn't send the tickets of the play to"], ["took the tickets of the play from/didn't take the tickets of the play from"]],
        "packed_predicates": ["wasn't interested in it/was interested in it", "was eager to see it/wasn't eager to see it"],
    },
    {
        "index": 261,
        "orig_sentence": "Kirilov ceded the presidency to Shatov because [he] was less popular.",
        "entities": ["James", "Amy"],
        "entity_substitutes": [["Robert", "Jack"], ["Donna", "Emily"]],
        "packed_relations": ["ceded the presidency to/didn't cede the presidency to", "took over the presidency from/didn't take over the presidency from"],
        "packed_relation_substitutes": [["gave the presidency to/didn't give the presidency to"], ["got the presidency from/didn't get the presidency from"]],
        "packed_predicates": ["was notorious/was not notorious", "was popular/wasn't popular"],
    },
]
